replicaCount: 1

image:
  pullPolicy: IfNotPresent
  pullSecrets: []
nameOverride: order-service
fullnameOverride: order-service

postgresql:
  fullnameOverride: postgres
  postgresqlUsername: postgres
  postgresqlPassword: "12345"
  postgresqlDatabase: postgres
  postgresqlAppDatabase: order_service
  persistence:
    size: 1Gi
  service:
    port: "5432"


serviceAccount:
  create: true
  annotations: {}
  name: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

autoscaling:
  enabled: false