apiVersion: v1
kind: ConfigMap
metadata:
  name: uaa-configmap
data:
  uaa.yml: |-
{{ .Files.Get "uaa.yml" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: log4j-configmap
data:
  log4j2.properties: |-
{{ .Files.Get "log4j2.properties" | indent 4 }}