apiVersion: v2
name: event-sourcing
description: Eve

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

dependencies:
  - name: postgresql
    version: 9.x.x
    # repository: https://charts.bitnami.com/bitnami
    repository: file://deps/postgresql
    condition: postgresql.enabled
    tags:
      - database
  - name: gateway
    version: 0.x.x
    repository: file://deps/gateway
    tags:
      - gateway
  - name: keycloak
    version: 0.x.x
    repository: file://deps/keycloak
    tags:
      - auth-server
  - name: order-service
    version: 0.x.x
    repository: file://deps/order-service
    tags:
      - order-service