replicaCount: 1

service:
  port: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /api/$2
  hosts:
    - host: arch.homework
      paths:
        - /otusapp/dzakharov/api($|/)(.*)

authUrl: http://arch.homework/otusapp/dzakharov/auth
issuerUrl: http://arch.homework/otusapp/dzakharov/auth
discoveryService: discovery-service